### ISSUE TITLE
global states needs rework ?

### ISSUE THREAD

**Issue by noxthot** [kandolfp/ws23_ulg_vu_ama_performance#15]
pages/hpc/multithreading/#global_states states that _Without going into too much detail, `rand()` is not thread safe._

However, [the documentation](https://docs.julialang.org/en/v1/stdlib/Random/#Base.rand) states that _In a multi-threaded program, you should generally use different RNG objects from different threads or tasks in order to be thread-safe. However, the default RNG is thread-safe as of Julia 1.3 (using a per-thread RNG up to version 1.6, and per-task thereafter)._

On a sidenote, i think `:static` should also be used in `in_unit_circle_threaded4` (although the result luckily should not be affected).

**Comment by kandolfp** [comment]
Reformulate yes, `:static`  is not needed

**Comment by noxthot** [comment]
Should be fixed -> closed
