### ISSUE TITLE
formatting error

### ISSUE THREAD

**Issue by ziselsberger** [kandolfp/ws23_ulg_vu_ama_performance#19]
![image](https://github.com/kandolfp/ws23_ulg_vu_ama_performance/assets/129314046/b755f643-e0b6-4e2c-a20e-c9d5fa20ba76)

https://github.com/kandolfp/ws23_ulg_vu_ama_performance/blob/752b8d89ea303845d9be7f3210f56f02cbd0786f/pages/hpc/simd.md?plain=1#L8

**Comment by ziselsberger** [comment]
another one: 

<img width="888" alt="image" src="https://github.com/kandolfp/ws23_ulg_vu_ama_performance/assets/129314046/7014c93d-e2aa-4516-a68b-5aaf00eea19f">

https://github.com/kandolfp/ws23_ulg_vu_ama_performance/blob/a2582ac2972f2a453ef90ae63b40dda60e992935/pages/remote-computing/hpc/architecture.md?plain=1#L42

**Comment by noxthot** [comment]
fixed ty -> closed
