### ISSUE TITLE
Update Franklin

### ISSUE THREAD

**Issue by kandolfp** [kandolfp/ws23_ulg_vu_ama_performance#2]
Franklin has seen updates and we should include them

**Comment by kandolfp** [comment]
https://github.com/tlienart/Xranklin.jl Will be the new Franklin.jl but I'm not sure if we should already go there, given our limited time. After the workshop a port would be nice to give the developers some feedback

**Comment by noxthot** [comment]
I have already looked at Xranklin once, but it is still in a very, very early alpha stage. The only release is `0.0.1` and that was ages ago. That's why I wouldn't do anything for this course there.

And in the existing repository, Franklin is already on the latest version `0.10.93`.

**Comment by kandolfp** [comment]
I forgot that I did update the packages but not the julia version...
